### ISSUE TITLE
Errors to be cleared

### ISSUE THREAD

**Issue by LiMinggang** [LiMinggang/bitswash#1]
20:10:17: Can't read value of 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run\Bitswash' (error 2: 系统找不到指定的文件。)
20:10:17: Can't read value of 'HKCU\Software\Classes\.torrent\Old_Default' (error 2: 系统找不到指定的文件。)
20:10:17: can't open file 'C:\bitswash\build\msw\vc14.2\x64\Debug\save_history' (error 2: 系统找不到指定的文件。)
20:10:17: Failed opening download path history file C:\bitswash\build\msw\vc14.2\x64\Debug\save_history

20:10:17: can't open file 'C:\bitswash\build\msw\vc14.2\x64\Debug\open_history' (error 2: 系统找不到指定的文件。)
20:10:17: Failed opening download path history file C:\bitswash\build\msw\vc14.2\x64\Debug\open_history

**Comment by LiMinggang** [comment]
Fixed

**Comment by ghost** [comment]
I'm getting those errors too, but they don't seem to break anything
